name: adhoc_mentorlink_autoclose – availability

on:
  repository_dispatch:
    types: [adhoc-mentorlink-autoclose-submit]
  workflow_dispatch:
    inputs:
      write:
        description: "Write mode for this manual run"
        type: choice
        required: true
        default: dry
        options: [dry, live]
      ref:
        description: "Git ref to checkout (branch or SHA)"
        required: false
        default: feat/adhoc-mentorlink-autoclose
  schedule:
    - cron: "0 9 1-10 * *"   # days 1–10 at 09:00 UTC
    - cron: "0 18 1-10 * *"  # days 1–10 at 18:00 UTC

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: adhoc_mentorlink_autoclose
  cancel-in-progress: false

jobs:
  run-adhoc_mentorlink_autoclose:
    # Manual is always allowed. Cron/dispatch require toggles.
    if: ${{ github.event_name == 'workflow_dispatch'
           || (github.event_name == 'schedule' && vars.ENABLE_CRON == '1')
           || (github.event_name == 'repository_dispatch' && vars.ENABLE_DISPATCH == '1') }}

    runs-on: ubuntu-latest
    steps:
      - name: Resolve ref to checkout
        id: ref
        run: |
          if [ -n "${{ github.event.client_payload.ref }}" ]; then
            echo "value=${{ github.event.client_payload.ref }}" >> "$GITHUB_OUTPUT"
          elif [ -n "${{ inputs.ref }}" ]; then
            echo "value=${{ inputs.ref }}" >> "$GITHUB_OUTPUT"
          else
            echo "value=feat/adhoc-mentorlink-autoclose" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout repo (feature branch when provided)
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.ref.outputs.value }}

      - name: Debug toggles & ref
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Checked out ref: ${{ steps.ref.outputs.value }}"
          echo "ENABLE_CRON=${{ vars.ENABLE_CRON }}"
          echo "ENABLE_DISPATCH=${{ vars.ENABLE_DISPATCH }}"
          echo "ENABLE_WRITE=${{ vars.ENABLE_WRITE }}"
          echo "Manual write input=${{ inputs.write || 'n/a' }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/adhoc_mentorlink_autoclose/requirements.txt

      - name: Write Google service account key
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_ADHOCMENTORLINKAUTOCLOSE }}
        run: |
          echo "$GCP_SA_KEY" > "$RUNNER_TEMP/sa.json"

      - name: Resolve DRY_RUN
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ "${{ inputs.write }}" = "live" ]; then
              echo "DRY_RUN=0" >> "$GITHUB_ENV"
            else
              echo "DRY_RUN=1" >> "$GITHUB_ENV"
            fi
          else
            if [ "${{ vars.ENABLE_WRITE }}" = "1" ]; then
              echo "DRY_RUN=0" >> "$GITHUB_ENV"
            else
              echo "DRY_RUN=1" >> "$GITHUB_ENV"
            fi
          fi
          echo "Effective DRY_RUN=$(grep '^DRY_RUN=' $GITHUB_ENV | tail -n1 | cut -d= -f2)"

      - name: Run automation script
        env:
          GCP_SA_KEY_FILE: ${{ runner.TEMP }}/sa.json
          SHEET_ID: ${{ vars.SHEET_ID }}
          SHEET_WORKSHEET_TITLE: ${{ vars.SHEET_WORKSHEET_TITLE }}
          MENTORS_YML_PATH: _data/mentors.yml
          TIMEZONE: Europe/London
        run: |
          python tools/adhoc_mentorlink_autoclose/auto_close_mentors.py

      - name: Create Pull Request
        if: ${{ always() }}
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "adhoc_mentorlink_autoclose: close full mentors for {{date}}"
          title: "adhoc_mentorlink_autoclose: capacity reached – run ${{ github.run_id }}"
          body: |
            Automation: adhoc_mentorlink_autoclose
            Trigger: `${{ github.event_name }}` (type: `${{ github.event.action }}`)
            Branch ref: `${{ steps.ref.outputs.value }}`
            Timezone: Europe/London
            Sheet ID: `${{ vars.SHEET_ID }}`
            DRY_RUN: `${{ env.DRY_RUN }}`
            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          add-paths: |
            _data/mentors.yml
          branch: automation/adhoc-mentorlink-autoclose
          branch-suffix: short-commit-hash
          delete-branch: true
          base: main

      - name: Print PR link (if any)
        if: ${{ steps.cpr.outputs.pull-request-url }}
        run: |
          echo "Pull Request URL: ${{ steps.cpr.outputs.pull-request-url }}"